### PR TITLE
added SASI indexes for results and objects.

### PR DESCRIPTION
**Pull request by webstergd**
This pull request add [SASI](https://github.com/apache/cassandra/blob/trunk/doc/SASI.md) second level indexing for results, submissions, and objects. 
    - Does not include complex queries (sets) because it is not yet supported by Cassandra

### CODE REVIEW

**Comment by webstergd** [comment]
Ready for review

**Comment by webstergd** [comment]
Now also adds some documentation to help with issue #5

**Comment by cynexit** [comment]
Looks good, builds and runs successful. We might want to add to the documentation that C* 3.5 is required because of the indexes.

**Comment by webstergd** [comment]
I added some text in README.md. Should I make this more explicit?

**Comment by cynexit** [comment]
The README is totally fine, just a heads-up for the main documentation later on.

**Pull request merged**
